import Link from "next/link";
import { Boxes, Mail, MapPin, Phone } from "lucide-react";

type Props = { seller: { tradingName: string; description?: string | null; phone?: string | null; email?: string | null; addressLine1?: string | null; city?: string | null; district?: string | null; country?: string | null; taxNumber?: string | null; registrationNumber?: string | null }; sellerSlug: string };
export function PublicFooter({ seller, sellerSlug }: Props) {
  const base = "";
  return <footer id="contact" className="bg-[#06294f] text-white"><div className="site-container grid gap-9 py-12 md:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full border-2 border-red-500 text-red-400"><Boxes className="h-5 w-5" /></div><div><div className="font-black uppercase">{seller.tradingName}</div><div className="text-[9px] font-bold uppercase tracking-[.22em] text-blue-200">B2B dealer platform</div></div></div><p id="about" className="mt-4 max-w-md text-xs leading-6 text-blue-100/70">{seller.description || "Dealer commerce for tractors, spare parts, agricultural implements, accessories, lubricants and workshop tools in Nepal."}</p>{(seller.taxNumber || seller.registrationNumber) && <div className="mt-3 text-[10px] text-blue-200/60">{seller.taxNumber && <span>PAN/VAT: {seller.taxNumber}</span>} {seller.registrationNumber && <span className="ml-3">Registration: {seller.registrationNumber}</span>}</div>}</div>
    <FooterColumn title="Company" links={[["Products",`${base}/products`],["How it works",`${base}#how-it-works`],["Dealer network",`${base}#dealer-network`],["Request dealership",`${base}/request-dealership`]]} /><FooterColumn title="Dealer" links={[["Seller login",`${base}/login`],["Product catalogue",`${base}/products`],["Order workflow",`${base}#how-it-works`],["Dealer benefits",`${base}#dealer-network`]]} />
    <div><h3 className="text-xs font-black uppercase tracking-wider">Contact</h3><div className="mt-4 space-y-3 text-[11px] leading-5 text-blue-100/75"><div className="flex gap-2"><MapPin className="mt-1 h-3.5 w-3.5 shrink-0 text-red-400" />{[seller.addressLine1, seller.city, seller.district, seller.country].filter(Boolean).join(", ")}</div>{seller.phone && <a href={`tel:${seller.phone}`} className="flex gap-2"><Phone className="h-3.5 w-3.5 text-red-400" />{seller.phone}</a>}{seller.email && <a href={`mailto:${seller.email}`} className="flex gap-2 break-all"><Mail className="h-3.5 w-3.5 text-red-400" />{seller.email}</a>}</div></div></div><div className="border-t border-white/10"><div className="site-container flex flex-col justify-between gap-2 py-5 text-[10px] text-blue-100/50 sm:flex-row"><span>© {new Date().getFullYear()} {seller.tradingName}. All rights reserved.</span><span>Bageshwari B2B · Nepal · NPR</span></div></div></footer>;
}

function FooterColumn({ title, links }: { title: string; links: string[][] }) { return <div><h3 className="text-xs font-black uppercase tracking-wider">{title}</h3><ul className="mt-4 space-y-2.5">{links.map(([label, href]) => <li key={label}><Link href={href} className="text-[11px] text-blue-100/70 hover:text-white">{label}</Link></li>)}</ul></div>; }
